name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.10  # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm ci  # Use npm ci for clean install

      - name: Build the project
        run: npm run build  # Assumes 'build' script is defined in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          publish_dir: ./dist  # Directory with the build output
          publish_branch: gh-pages  # Branch to which the site is deployed
